In [ ]:
%matplotlib notebook
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from glue import BlindNavigator
from utility import read_video
from PIL import Image
import numpy as np
import cv2
import time

class Visor(object):
    def __init__(self, form = 'OFFLINE'):
        self.form = form
        self.handler = None
        self.handler2 = None
        
    def initializer(self):
        if self.form == 'OFFLINE':
            self.fourcc = cv2.VideoWriter_fourcc(*'XVID')
            writer = None
            (h, w) = (None, None)
            self.handler = writer 
            
        else:
            fig = plt.figure(figsize=(16, 10))
            ax = fig.add_axes([0,0,1,1])

            plt.ion()
            fig.show()
            fig.canvas.draw()
            self.handler = fig
            self.handler2 = ax

            
    def inliner(self, im, save_path='./test.avi'):
        if self.form == 'OFFLINE' and self.handler is None:
            (h, w) = im.shape[:2]
            self.handler = cv2.VideoWriter(save_path, self.fourcc, 30, (w, h), True)
    
    def drawer(self, im):
        if self.form == 'OFFLINE':
            self.handler.write(im)
        else:
            self.handler2.imshow(im)
            self.handler.canvas.draw()
            self.handler2.clear()
debuger = 'OFFLINE'
def test_det_track():
    video_path = 'data/IMG_1051.MOV'
    save_path = 'IMG_1051_det_track.avi'

    visor = Visor(debuger)
    visor.initializer()

    navigator = BlindNavigator()
    timestamps = [time.time()]
    for data in read_video(video_path):
        timestamps.append(time.time())

        traffic_lights, detected_obstacles = navigator.detect_traffic_light(data)
        timestamps.append(time.time())
        print('Processing time: %.3f'%(timestamps[-1] - timestamps[-2]))
        data = cv2.cvtColor(data, cv2.COLOR_BGR2RGB)
        visor.inliner(data, save_path)
        for (id_, bbox) in traffic_lights:
            
            bbox = bbox.astype(int)
            assert  id_ < len(navigator.traffic_light_pool.trackers), 'id_ not valid'
#             bbox = [bbox[0] / data.shape[1], bbox[1] / data.shape[0], bbox[2] / data.shape[1], bbox[3] / data.shape[0]]
#             print(bbox)
#             p = patches.Rectangle((bbox[0], bbox[1]), bbox[2]-bbox[0], bbox[3]-bbox[1], fill=False, alpha=1)
#             ax.add_patch(p)
            cv2.rectangle(data, tuple(bbox[:2]),tuple(bbox[2:4]), [255, 0, 0], 3)
        visor.drawer(data)

def test_light_classifier():
    video_path = 'data/IMG_1051.MOV'
    save_path = 'IMG_1051_det_track_cls.avi'

    visor = Visor(debuger)
    visor.initializer()
    navigator = BlindNavigator()
    for data in read_video(video_path):
        traffic_lights, detected_obstacles = navigator.detect_traffic_light(data)
        light_states = navigator.color_classify_by_boxes(data, [light[1] for light in traffic_lights])
        data = cv2.cvtColor(data, cv2.COLOR_BGR2RGB)
        visor.inliner(data, save_path)
        for (id_, bbox), state in zip(traffic_lights, light_states):
            
            bbox = bbox.astype(int)
            assert  id_ < len(navigator.traffic_light_pool.trackers), 'id_ not valid'
#             bbox = [bbox[0] / data.shape[1], bbox[1] / data.shape[0], bbox[2] / data.shape[1], bbox[3] / data.shape[0]]
#             print(bbox)
#             p = patches.Rectangle((bbox[0], bbox[1]), bbox[2]-bbox[0], bbox[3]-bbox[1], fill=False, alpha=1)
#             ax.add_patch(p)
            cv2.rectangle(data, tuple(bbox[:2]),tuple(bbox[2:4]), [255, 0, 0], 3)
            font = cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(data, '%s'%(state), (bbox[0]-1,bbox[1]-1), font, 1, color=(255,255,0), thickness=2)
        visor.drawer(data)


        
        
        
if __name__ == '__main__':
    test_det_track()

/home/changcheng/anaconda3/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


keras_yolo3/model_data/yolo.h5 model, anchors, and classes loaded.
get frame 0
[0.2054599  0.0137211  0.01778067 ... 0.19325048 0.09076633 0.08210257]
[0.         0.00511656 0.00028194 ... 0.14154416 0.13942064 0.13884631]
[0.4        0.         0.         ... 0.19057007 0.15867716 0.1281939 ]
[0.         0.         0.         ... 0.12139461 0.12727863 0.12811518]
[0.         0.         0.         ... 0.12570392 0.16845728 0.12281688]
Processing time: 3.419
get frame 1
[0.17526558 0.0016417  0.00219152 ... 0.17639543 0.08928764 0.08293206]
[0.02011634 0.         0.02837306 ... 0.1147473  0.10500809 0.10616661]
[0.4        0.09498732 0.00423655 ... 0.24538743 0.06657743 0.05962665]
[0.0107201  0.00045561 0.00855878 ... 0.14880538 0.14800116 0.14576644]
[0.08483052 0.05292986 0.         ... 0.16334932 0.1662525  0.16147214]
[0.00175221 0.         0.01780435 ... 0.19398238 0.23697749 0.17318474]
[0.4        0.06402964 0.         ... 0.20460775 0.17759801 0.13419189]
[0.3189848  0.02916615

[0.         0.         0.         ... 0.14803527 0.160458   0.16058032]
[0.         0.         0.         ... 0.09470044 0.1397967  0.17424445]
[0.00059424 0.         0.         ... 0.1383461  0.15642351 0.14224587]
[0.1680376  0.         0.0130572  ... 0.11668392 0.11896212 0.10773389]
[0.38745746 0.02342767 0.08890175 ... 0.11508793 0.16312867 0.11813826]
[0.01995618 0.00405667 0.02565664 ... 0.11328233 0.0835266  0.11476981]
Processing time: 0.168
get frame 9
[0.26225662 0.4        0.01384581 ... 0.12227266 0.11963499 0.11066208]
[0.01900364 0.06931445 0.         ... 0.16327609 0.16450027 0.14984357]
[0.38836    0.38116026 0.0811105  ... 0.16036533 0.14754623 0.12952307]
[0.18732764 0.08900606 0.00338102 ... 0.14649148 0.1631691  0.13756964]
[0.33063933 0.10357612 0.02419856 ... 0.12993795 0.1847422  0.12705459]
[0.00574071 0.06416071 0.         ... 0.17677152 0.19640698 0.1793036 ]
[0.03203097 0.         0.04529862 ... 0.18481119 0.14047475 0.10907451]
[0.         0.         0.0081

[0.0495621  0.0443297  0.0233638  ... 0.24864416 0.1490659  0.10902076]
[0.2048133  0.06702255 0.24680442 ... 0.16809537 0.14808805 0.10861723]
[0.00503517 0.         0.         ... 0.14029609 0.09439477 0.10821906]
[0.         0.01055061 0.         ... 0.13280284 0.14445573 0.14359123]
[0.         0.         0.0007352  ... 0.08380086 0.11975557 0.15270546]
[0.         0.         0.         ... 0.13597615 0.15662298 0.14029945]
[0.         0.         0.         ... 0.09567003 0.10991546 0.09887772]
[0.         0.         0.         ... 0.12809722 0.16588178 0.12632236]
[0.         0.         0.         ... 0.14023621 0.09754246 0.14773503]
Processing time: 0.200
get frame 17
[0.37366605 0.18650696 0.27599695 ... 0.12412189 0.10937275 0.10205312]
[0.03125095 0.02164584 0.03189034 ... 0.1573645  0.15907942 0.14295502]
[0.38679203 0.28179085 0.18418369 ... 0.1714814  0.15105645 0.12944202]
[0.00846991 0.03151792 0.00305096 ... 0.16707234 0.19504434 0.17496428]
[0.0895246  0.17224196 0.   

[0.19706365 0.09438064 0.05377734 ... 0.156869   0.16420476 0.15334949]
[0.00469541 0.00316476 0.         ... 0.19877592 0.25532404 0.20955753]
[0.12323888 0.02922717 0.         ... 0.27117586 0.1596481  0.1083079 ]
[0.31236875 0.07480638 0.10976315 ... 0.28319603 0.15549402 0.10373086]
[0.01430107 0.00456831 0.         ... 0.2026039  0.12256906 0.15724444]
[0.         0.01518487 0.00962492 ... 0.11365668 0.11746575 0.11748186]
[0.         0.         0.         ... 0.08555263 0.1145803  0.13621646]
[0.         0.00515347 0.         ... 0.13686363 0.1561526  0.1402272 ]
[0.         0.         0.         ... 0.11052268 0.18456909 0.1071085 ]
[0.         0.         0.         ... 0.09847718 0.12350329 0.09851445]
[0.         0.         0.         ... 0.10971344 0.08766449 0.10817209]
Processing time: 0.175
get frame 25
[0.19697356 0.18968296 0.16632666 ... 0.14343026 0.14547698 0.1332859 ]
[0.00495796 0.01287141 0.01311607 ... 0.14255504 0.15467745 0.14536686]
[0.20139664 0.21146005 0.066

[0.4        0.19796547 0.20345707 ... 0.31376553 0.26679856 0.29984695]
[0.         0.         0.         ... 0.13562869 0.15686858 0.1578231 ]
[0.         0.         0.         ... 0.09331544 0.12304763 0.14677188]
[0.         0.00475868 0.         ... 0.13601801 0.15618488 0.14057271]
[0.         0.         0.         ... 0.12278032 0.17158382 0.12175528]
[0.         0.         0.         ... 0.09387213 0.11021459 0.09587131]
[0.         0.         0.         ... 0.10811184 0.11728214 0.10634036]
Processing time: 0.147
get frame 33
[0.3976007  0.1910688  0.00203615 ... 0.18610567 0.16994183 0.13258319]
[0.3370953  0.18503988 0.03397698 ... 0.13830476 0.12401342 0.11538155]
[0.3916271  0.13050726 0.02362041 ... 0.1593295  0.1297833  0.10467852]
[0.04462539 0.08374931 0.00396074 ... 0.16759656 0.18392973 0.16987787]
[0.19285071 0.10865116 0.         ... 0.14692321 0.15738198 0.14501204]
[0.01596504 0.00314139 0.00382074 ... 0.17440303 0.26182216 0.18734378]
[0.141458   0.         0.001

[0.36389568 0.         0.02082531 ... 0.13700645 0.14510985 0.13539352]
[0.4        0.15447512 0.010619   ... 0.11746646 0.17627408 0.11314034]
[0.05544017 0.         0.         ... 0.18663603 0.21180722 0.1940976 ]
[0.1078948  0.         0.15258627 ... 0.23961388 0.32743365 0.2434822 ]
[0.16505443 0.05121786 0.06941362 ... 0.23681343 0.28720292 0.18315776]
[0.35719687 0.01569258 0.35138896 ... 0.32260877 0.31557822 0.30939144]
[0.00118795 0.00132816 0.         ... 0.09603173 0.12333412 0.13155653]
[0.         0.         0.         ... 0.07923901 0.11221755 0.13941623]
[0.00188335 0.         0.         ... 0.14915586 0.17599104 0.15690324]
[0.         0.         0.         ... 0.12667754 0.17097175 0.12208109]
[0.06357983 0.         0.         ... 0.09776334 0.11075543 0.10027887]
[0.         0.         0.         ... 0.09369782 0.08168457 0.09341854]
Processing time: 0.152
get frame 41
[0.4        0.15071632 0.17507508 ... 0.16081226 0.1437385  0.13164164]
[0.33398378 0.11216218 0.096

[0.23492905 0.         0.         ... 0.08350713 0.09155961 0.08645548]
[0.4        0.09438081 0.02387667 ... 0.10759086 0.07205869 0.11070562]
Processing time: 0.146
get frame 48
[0.3971018  0.31650275 0.05245821 ... 0.1579202  0.14192013 0.13341098]
[0.29026756 0.35808736 0.11128315 ... 0.15305579 0.14620802 0.1378603 ]
[0.29852208 0.2734492  0.04693415 ... 0.14840767 0.1312811  0.10792596]
[0.06119924 0.00894538 0.0019754  ... 0.17736624 0.19530931 0.18254796]
[0.16651209 0.04477434 0.00601654 ... 0.1622827  0.18110241 0.15843672]
[0.         0.00609721 0.         ... 0.18962348 0.24881946 0.19369821]
[0.10541318 0.         0.14650646 ... 0.18341722 0.2629311  0.16824971]
[0.0462081  0.         0.06316984 ... 0.26746896 0.25636092 0.17335267]
[0.16760638 0.11757782 0.17196384 ... 0.16229653 0.22792897 0.16857363]
[0.         0.         0.         ... 0.0986997  0.12028532 0.12960838]
[0.         0.         0.         ... 0.08191235 0.1142347  0.13919161]
[0.         0.         0.   

[0.4        0.01206057 0.35729468 ... 0.23517807 0.21794115 0.20696428]
[0.00181916 0.         0.         ... 0.09835654 0.11848486 0.12656617]
[0.         0.         0.         ... 0.09695707 0.14562047 0.18071128]
[0.         0.         0.00074695 ... 0.13338016 0.14823417 0.138723  ]
[0.13484457 0.09230255 0.         ... 0.1403948  0.16484211 0.13952008]
[0.25258642 0.00403429 0.10716335 ... 0.12337118 0.14053424 0.12773615]
[0.         0.         0.12141486 ... 0.12619866 0.14399002 0.12505206]
Processing time: 0.153
get frame 56
[0.4        0.3753908  0.11174682 ... 0.16815168 0.16816051 0.15386575]
[0.07561415 0.18768868 0.03815724 ... 0.14980312 0.15066345 0.13735649]
[0.3245233  0.15775132 0.07536792 ... 0.15695524 0.13420174 0.12152231]
[0.03561759 0.01575534 0.02839064 ... 0.16438405 0.17518768 0.16810234]
[0.07358245 0.04611602 0.00689792 ... 0.15859564 0.19071962 0.14483194]
[0.00914471 0.         0.00685019 ... 0.19349407 0.25423175 0.20078614]
[0.15415095 0.06628692 0.114

get frame 63
[0.08835584 0.21425058 0.06235844 ... 0.197453   0.1746461  0.17261493]
[0.00021962 0.00684102 0.01647579 ... 0.19465967 0.17327979 0.16067624]
[0.35254446 0.37469265 0.03416512 ... 0.1368953  0.13235033 0.12618159]
[0.02141419 0.         0.         ... 0.19102694 0.2148286  0.19393606]
[0.19917585 0.         0.01009152 ... 0.17794085 0.22444478 0.16699596]
[0.         0.00077016 0.03852794 ... 0.22545922 0.275057   0.22877464]
[0.         0.         0.         ... 0.2342263  0.3234985  0.19704814]
[0.         0.         0.         ... 0.2766503  0.2870212  0.19672605]
[0.18981186 0.         0.         ... 0.16778518 0.25152814 0.16992693]
[0.         0.         0.         ... 0.09449136 0.11859562 0.13340971]
[0.         0.         0.         ... 0.09016883 0.13840361 0.18035002]
[0.         0.00505493 0.00862893 ... 0.15281373 0.17687368 0.16261712]
[0.32866675 0.         0.13181037 ... 0.12565199 0.1570101  0.12477284]
[0.4        0.         0.         ... 0.12168874 0.

[0.06888044 0.113061   0.08656976 ... 0.17642921 0.16617736 0.16509996]
[0.19315128 0.1809411  0.08411452 ... 0.16904628 0.15455782 0.13869865]
[0.06901661 0.00119151 0.         ... 0.1640188  0.17755026 0.16828646]
[0.32729405 0.01831676 0.         ... 0.13994814 0.15877181 0.13426451]
[0.         0.         0.00951062 ... 0.22388254 0.28267562 0.24346802]
[0.20254426 0.05146622 0.0358051  ... 0.22051817 0.30993614 0.18992798]
[0.         0.         0.         ... 0.276833   0.29127705 0.18907444]
[0.4        0.34666565 0.20937666 ... 0.17941737 0.2351483  0.18083964]
[0.00481086 0.         0.         ... 0.12448283 0.15234464 0.16051337]
[0.00384978 0.         0.         ... 0.09370039 0.16594027 0.20049854]
[0.01543944 0.         0.         ... 0.169894   0.18309271 0.1772158 ]
[0.4        0.01745443 0.         ... 0.11819614 0.15078102 0.11610238]
[0.4        0.         0.         ... 0.10692652 0.1217467  0.10747597]
[0.4        0.         0.         ... 0.10075565 0.1280671  0.10

[0.         0.10435791 0.0390009  ... 0.1566251  0.15395975 0.15167423]
[0.17798391 0.05838706 0.11648768 ... 0.15840204 0.14653443 0.129966  ]
[0.09812049 0.03388375 0.         ... 0.19614138 0.2215739  0.21041714]
[0.26456532 0.08721925 0.00736095 ... 0.16586715 0.18262424 0.16280703]
[0.         0.00858362 0.         ... 0.22716649 0.3022782  0.24843036]
[0.03222795 0.01137851 0.         ... 0.1797324  0.26124462 0.16058728]
[0.17109457 0.03624262 0.         ... 0.21990336 0.24737686 0.14103854]
[0.06190186 0.         0.4        ... 0.2133175  0.23348884 0.20393509]
[0.         0.         0.         ... 0.11850158 0.13633084 0.13675019]
[0.         0.         0.         ... 0.08634509 0.14095864 0.17318173]
[0.00626665 0.         0.         ... 0.1360979  0.152887   0.14009987]
[0.4        0.         0.         ... 0.11720451 0.14819205 0.12249558]
[0.4        0.         0.         ... 0.09288688 0.10181185 0.09631976]
[0.4        0.         0.         ... 0.10076392 0.11852076 0.10

[0.00744828 0.         0.         ... 0.13298759 0.17585644 0.1337026 ]
[0.         0.         0.         ... 0.12308167 0.14856742 0.11159178]
[0.06088909 0.0907681  0.         ... 0.13000005 0.14289701 0.12561753]
[0.02847863 0.         0.         ... 0.11928552 0.08513758 0.11920882]
Processing time: 0.151
get frame 87
[0.33536294 0.08731293 0.09064542 ... 0.1908686  0.16256712 0.14146788]
[0.1477695  0.287848   0.         ... 0.17817724 0.1586796  0.13935204]
[0.31430942 0.11248918 0.11796099 ... 0.16343105 0.14439262 0.11661615]
[0.15141654 0.11664946 0.         ... 0.18062308 0.20194528 0.18926823]
[0.32184976 0.17970741 0.02172781 ... 0.15404509 0.18395318 0.1539035 ]
[0.         0.02393387 0.0052906  ... 0.20687576 0.278959   0.22038206]
[0.02686802 0.         0.         ... 0.14501368 0.2116748  0.13883795]
[0.00345639 0.         0.1450127  ... 0.21392675 0.27506533 0.19357996]
[0.16738945 0.03729548 0.02004572 ... 0.14631923 0.17108326 0.16703248]
[0.         0.         0.   

[0.4        0.1069186  0.1238011  ... 0.19378349 0.15890072 0.1398529 ]
[0.4        0.3090678  0.         ... 0.14016347 0.12186583 0.11363437]
[0.39565685 0.22224718 0.06633146 ... 0.19203672 0.15523478 0.11955659]
[0.0349835  0.02700532 0.         ... 0.24095306 0.29065016 0.23380618]
[0.32644123 0.12135147 0.01040462 ... 0.1849371  0.19031176 0.18534425]
[0.00110629 0.00553849 0.         ... 0.20089649 0.26762524 0.19663547]
[0.         0.         0.00766476 ... 0.15443209 0.1527631  0.14563823]
[0.00202175 0.00479499 0.         ... 0.200422   0.15331753 0.14607304]
[0.04521611 0.02068083 0.         ... 0.15681837 0.16575977 0.16276468]
[0.         0.         0.         ... 0.14230876 0.15340893 0.1528019 ]
[0.         0.         0.00780474 ... 0.08732715 0.11981669 0.1377575 ]
[0.00428839 0.00799095 0.         ... 0.14138708 0.15608114 0.14268032]
[0.         0.         0.         ... 0.15177917 0.20441462 0.13516329]
[0.         0.         0.         ... 0.12366359 0.12389507 0.12

[0.4        0.2237587  0.05534416 ... 0.15596603 0.12714358 0.1168206 ]
[0.18224227 0.12196477 0.07665843 ... 0.15074416 0.13497846 0.13499884]
[0.3976295  0.2052666  0.0284428  ... 0.17798497 0.13739198 0.12794532]
[0.01426723 0.00991573 0.         ... 0.12399693 0.20988189 0.19728434]
[0.19645058 0.01531265 0.02842775 ... 0.18625951 0.22255658 0.18888374]
[0.0102838  0.00080061 0.         ... 0.13551281 0.2262988  0.22535662]
[0.         0.         0.         ... 0.1999615  0.09497502 0.10156399]
[0.         0.         0.02375031 ... 0.2827649  0.11446551 0.12464281]
[0.         0.         0.         ... 0.1938391  0.10195469 0.0963686 ]
[0.00302423 0.00034268 0.         ... 0.17185026 0.18025135 0.17894065]
[0.00180226 0.00601906 0.         ... 0.09960745 0.11836571 0.13291903]
[0.01796598 0.         0.         ... 0.1669524  0.19068722 0.17382175]
[0.         0.         0.         ... 0.12828857 0.13581856 0.12542696]
[0.         0.         0.         ... 0.13006383 0.13058794 0.11

[0.         0.         0.         ... 0.12044899 0.15219103 0.17307597]
[0.         0.01168434 0.         ... 0.14928313 0.16537733 0.15008995]
[0.         0.         0.         ... 0.17045368 0.11841348 0.14593653]
[0.         0.         0.         ... 0.10645242 0.11133961 0.09815242]
[0.         0.         0.         ... 0.17569189 0.13387032 0.18010703]
Processing time: 0.151
get frame 111
[0.36771217 0.07608861 0.08389468 ... 0.17606468 0.13598269 0.12906343]
[0.1374597  0.         0.09949607 ... 0.1447303  0.13193728 0.13185732]
[0.4        0.19677016 0.03722869 ... 0.15088318 0.12742646 0.1182889 ]
[0.00489921 0.00282115 0.         ... 0.1450668  0.17155668 0.14998756]
[0.11348571 0.00793395 0.         ... 0.13714813 0.18713062 0.131783  ]
[0.         0.         0.0174134  ... 0.17252538 0.22301146 0.18756415]
[0.2027184  0.01970835 0.07728089 ... 0.14726387 0.11522107 0.11176601]
[0.04847961 0.         0.00652957 ... 0.19430405 0.12379199 0.13509068]
[0.4        0.01481305 0.01

[0.00780084 0.01925242 0.0054437  ... 0.17009382 0.15215857 0.13769887]
[0.39069632 0.10311858 0.1385526  ... 0.16389678 0.1414488  0.13031729]
[0.003069   0.02303043 0.04738626 ... 0.26264843 0.22173122 0.22725102]
[0.08724278 0.00477363 0.03601881 ... 0.30625036 0.2914717  0.28696448]
[0.00395256 0.         0.00571842 ... 0.26324192 0.2216754  0.21829703]
[0.4        0.22900748 0.13549688 ... 0.1777495  0.18471275 0.16317102]
[0.4        0.09550484 0.2963864  ... 0.18782946 0.19842586 0.17230617]
[0.3318254  0.02651807 0.         ... 0.2586682  0.23942712 0.23412953]
[0.         0.         0.         ... 0.12588781 0.12973419 0.12954992]
[0.         0.         0.         ... 0.11458525 0.14571084 0.16218166]
[0.         0.01669859 0.         ... 0.13732114 0.14808792 0.13737218]
[0.4        0.04173684 0.08138262 ... 0.15287347 0.13654591 0.12558538]
[0.4        0.3417935  0.39724168 ... 0.13517499 0.13601598 0.12775932]
[0.4        0.         0.04228761 ... 0.1642217  0.10968305 0.15

[0.4        0.32802463 0.02286627 ... 0.14514124 0.13612589 0.13157704]
[0.14650114 0.17793398 0.02156552 ... 0.19586605 0.18675321 0.18263236]
[0.4        0.27675617 0.08264576 ... 0.17157134 0.1308833  0.12087091]
[0.03101475 0.02700413 0.03170566 ... 0.13971445 0.12218756 0.12402134]
[0.15191522 0.12866111 0.         ... 0.14294013 0.12786257 0.12946641]
[0.         0.00614675 0.0052077  ... 0.19354999 0.12850387 0.12772664]
[0.1830258  0.03611101 0.15225738 ... 0.12729007 0.17201912 0.15593027]
[0.0594824  0.         0.23543927 ... 0.17159961 0.2198906  0.19257404]
[0.22857781 0.         0.30928993 ... 0.18959229 0.22409558 0.21497183]
[0.         0.         0.         ... 0.1259677  0.14395386 0.14569761]
[0.         0.         0.         ... 0.08581239 0.11257017 0.13038033]
[0.         0.         0.         ... 0.16128522 0.18332727 0.16895172]
[0.         0.         0.         ... 0.1150377  0.1225827  0.10264284]
[0.         0.         0.         ... 0.10024542 0.12316705 0.09

[0.35817608 0.27936357 0.35793605 ... 0.16807064 0.18424481 0.16392452]
[0.0000000e+00 1.9698068e-02 9.1224763e-05 ... 1.5124170e-01 1.7238533e-01
 1.5864731e-01]
[0.         0.         0.         ... 0.105763   0.13042213 0.13728446]
[0.         0.0104552  0.         ... 0.15815611 0.19260424 0.16471568]
[0.11214557 0.01090283 0.         ... 0.1053508  0.14639215 0.1058897 ]
[0.17281215 0.11496785 0.05049448 ... 0.09025636 0.10150772 0.09099303]
[0.01269447 0.01774107 0.03141722 ... 0.09949825 0.09177281 0.09788974]
Processing time: 0.188
get frame 134
[0.2532924  0.36992145 0.00581743 ... 0.13839024 0.12607843 0.12037903]
[0.02291128 0.10979127 0.03932019 ... 0.18299639 0.15041089 0.15523314]
[0.4        0.21691293 0.         ... 0.16389802 0.12299566 0.11400215]
[0.00269067 0.00366833 0.         ... 0.15589885 0.15854381 0.15153104]
[0.03522656 0.01583385 0.01533924 ... 0.15653601 0.17265272 0.1401363 ]
[0.         0.         0.0384201  ... 0.2036931  0.23343378 0.20756358]
[0.12136

[0.11110855 0.         0.         ... 0.10113537 0.07370429 0.09936931]
[0.         0.         0.         ... 0.10024061 0.14797926 0.09966481]
[0.         0.         0.01281874 ... 0.1756528  0.12299779 0.16830519]
Processing time: 0.151
get frame 142
[0.04378063 0.04565382 0.         ... 0.16440889 0.14945456 0.14110251]
[0.00401245 0.00537469 0.00647133 ... 0.18608627 0.16115303 0.14795576]
[0.4        0.3337678  0.05036751 ... 0.12933871 0.1251969  0.11669494]
[0.08164501 0.026693   0.00289374 ... 0.19244742 0.2044233  0.19008519]
[0.15167104 0.01357708 0.00348823 ... 0.16421829 0.17488143 0.15569362]
[0.         0.0059803  0.00572685 ... 0.19402386 0.24961227 0.1931758 ]
[0.20915091 0.10203832 0.13803256 ... 0.18197766 0.24244505 0.19181249]
[0.03310994 0.00634595 0.02809472 ... 0.22103687 0.2534118  0.22660683]
[0.30096537 0.024823   0.09419665 ... 0.12460545 0.1360138  0.11544013]
[0.         0.         0.         ... 0.0971076  0.11355838 0.11930273]
[0.         0.         0.  

[0.         0.         0.         ... 0.15418684 0.18819849 0.13919123]
[0.         0.         0.         ... 0.13042022 0.10673493 0.12917306]
Processing time: 0.167
get frame 150
[0.3212099  0.22412102 0.0808003  ... 0.1292704  0.12296078 0.11461769]
[0.00993779 0.05139733 0.04913789 ... 0.16307631 0.15968138 0.15217257]
[0.4        0.23619983 0.12266469 ... 0.14562462 0.12004295 0.10689542]
[0.02309884 0.         0.01733952 ... 0.17051473 0.18379912 0.17080377]
[0.28439403 0.02797234 0.02331406 ... 0.12966183 0.14588062 0.12527926]
[0.         0.00878103 0.00514461 ... 0.2096422  0.28080338 0.21664238]
[0.         0.         0.         ... 0.24547707 0.11982013 0.11375752]
[0.00141229 0.         0.         ... 0.3011185  0.11402654 0.09926665]
[0.         0.         0.         ... 0.19078578 0.19351254 0.186657  ]
[0.         0.         0.         ... 0.11387362 0.12007637 0.11523137]
[0.         0.         0.00820327 ... 0.10422897 0.11768904 0.11918265]
[0.00076002 0.00040928 0.  

[0.35703996 0.35785064 0.09481853 ... 0.15505883 0.15384918 0.14438635]
[0.17022462 0.13839236 0.00929097 ... 0.16456705 0.14469598 0.12012088]
[0.03651939 0.03889342 0.         ... 0.17298357 0.19468407 0.18112206]
[0.11401913 0.0755876  0.01149656 ... 0.1594163  0.19478196 0.15106608]
[0.         0.03544329 0.         ... 0.20592178 0.25897935 0.21804662]
[0.18393451 0.         0.05419222 ... 0.20958702 0.33668545 0.19365218]
[0.04490623 0.         0.2628597  ... 0.22804885 0.22546257 0.16357431]
[0.09979166 0.         0.         ... 0.1643721  0.26650286 0.16437647]
[0.         0.00096658 0.         ... 0.14257258 0.15945119 0.14966515]
[0.         0.         0.         ... 0.09725368 0.1181763  0.12989949]
[0.02322675 0.00122336 0.00077372 ... 0.141966   0.19720192 0.14876115]
[0.4        0.17899224 0.22640926 ... 0.09655819 0.10044782 0.09114274]
[0.1154192  0.04513777 0.04896821 ... 0.11303037 0.1351175  0.10839958]
[0.4        0.28392056 0.10774027 ... 0.14339948 0.11219469 0.14

[0.05673314 0.00507437 0.02246518 ... 0.16480914 0.26157194 0.15963414]
[0.0032564  0.         0.         ... 0.11869928 0.12591204 0.12149329]
[0.01253761 0.         0.         ... 0.09886331 0.11271882 0.12633218]
[0.         0.         0.         ... 0.15675023 0.19455075 0.16352296]
[0.4        0.         0.         ... 0.1127443  0.10933781 0.10627726]
[0.4        0.         0.         ... 0.14943834 0.18772668 0.13911436]
[0.03095039 0.         0.         ... 0.15849307 0.1181252  0.16235925]
Processing time: 0.150
get frame 166
[0.3701221  0.3420395  0.30625808 ... 0.19315685 0.18446545 0.16712913]
[0.05535176 0.02810385 0.08919338 ... 0.18213715 0.1776931  0.16925347]
[0.4        0.39295578 0.07135036 ... 0.1618277  0.13383265 0.12680818]
[0.01659228 0.03500254 0.         ... 0.21012338 0.23077455 0.21789204]
[0.14162666 0.0845135  0.         ... 0.18802275 0.24083377 0.17964898]
[0.03714861 0.00306116 0.01374015 ... 0.2076279  0.22874777 0.2124991 ]
[0.03099132 0.         0.  

[0.04669088 0.         0.         ... 0.11252852 0.1248633  0.11084374]
[0.         0.         0.         ... 0.11342992 0.13016595 0.10671155]
Processing time: 0.141
get frame 174
[0.15289448 0.08562308 0.02637298 ... 0.1874743  0.16848521 0.16000423]
[0.00240956 0.02789801 0.03722118 ... 0.19700557 0.13928679 0.14394662]
[0.4        0.21157303 0.0758325  ... 0.17038958 0.16385101 0.16083778]
[0.0323235  0.04636942 0.         ... 0.1832516  0.19974789 0.1896268 ]
[0.16447479 0.11588216 0.         ... 0.15785962 0.19835779 0.15201303]
[0.00993793 0.00111585 0.         ... 0.20024551 0.25523427 0.22381999]
[0.02654796 0.         0.         ... 0.16077672 0.17249542 0.15010697]
[0.         0.         0.         ... 0.15488198 0.21694699 0.13728529]
[0.39270285 0.         0.         ... 0.19391209 0.18035182 0.15383887]
[0.00397482 0.0004444  0.         ... 0.14191842 0.15719755 0.15012719]
[0.         0.         0.         ... 0.09344076 0.11972647 0.12660484]
[0.02789423 0.         0.00

[0.09332537 0.         0.         ... 0.16279644 0.2016003  0.15284894]
[0.03839048 0.         0.01567605 ... 0.20850685 0.27383098 0.21731317]
[0.2653471  0.         0.08303218 ... 0.20234808 0.28562024 0.17920709]
[0.         0.         0.         ... 0.22660579 0.24018334 0.16009215]
[0.4        0.         0.01947763 ... 0.14047354 0.21584085 0.1458339 ]
[0.         0.00626947 0.         ... 0.14005323 0.1630408  0.15931605]
[0.         0.         0.         ... 0.10076654 0.1521484  0.18649699]
[0.         0.00395843 0.         ... 0.13985898 0.15590072 0.14435887]
[0.03234691 0.         0.01429545 ... 0.1027269  0.13758248 0.10532513]
[0.         0.         0.         ... 0.09463667 0.10865473 0.09849051]
[0.3440878  0.         0.04343763 ... 0.09001444 0.13004693 0.09833308]
Processing time: 0.133
get frame 182
[0.35960102 0.12251791 0.         ... 0.17642133 0.16680852 0.15842217]
[0.03608854 0.00918803 0.05120867 ... 0.19120167 0.15431133 0.15422575]
[0.4        0.06949086 0.14

get frame 189
[0.3975133  0.24306086 0.16871342 ... 0.14687546 0.13590673 0.13236678]
[0.27394363 0.11547308 0.10630473 ... 0.19190349 0.16446723 0.15869667]
[0.4        0.07858218 0.086034   ... 0.11850169 0.09592077 0.0896128 ]
[0.00899211 0.00877561 0.01159385 ... 0.16334632 0.16931449 0.1642239 ]
[0.17442949 0.03492767 0.01089184 ... 0.14387432 0.16824096 0.13442612]
[0.         0.         0.03405723 ... 0.2114038  0.24178222 0.21816985]
[0.05255317 0.         0.         ... 0.18959466 0.2715326  0.18318555]
[0.17183444 0.         0.         ... 0.2371517  0.24840726 0.174862  ]
[0.         0.         0.         ... 0.12644045 0.19038518 0.12733659]
[0.00017821 0.         0.         ... 0.11248007 0.12967895 0.13377446]
[0.00154378 0.         0.00562606 ... 0.08581159 0.15278605 0.18522401]
[0.00398437 0.         0.         ... 0.15091895 0.16775322 0.1573768 ]
[0.4        0.12927443 0.17527425 ... 0.10125614 0.13027121 0.09972169]
[0.3677639  0.31906822 0.03740067 ... 0.11558448 0

[0.01785879 0.         0.         ... 0.10452385 0.11905847 0.10262091]
[0.20208536 0.         0.         ... 0.09170707 0.09732708 0.09239213]
[0.00662247 0.08884975 0.04682793 ... 0.10601821 0.12871158 0.10574844]
Processing time: 0.173
get frame 197
[0.4        0.3663677  0.1906847  ... 0.12994671 0.11378779 0.10709471]
[0.1849882  0.14785823 0.04284184 ... 0.18142246 0.14604437 0.14530815]
[0.4        0.29831398 0.05929962 ... 0.13949889 0.10501964 0.09924746]
[0.01372081 0.00849512 0.         ... 0.19477434 0.20248471 0.19584587]
[0.02789552 0.03617378 0.         ... 0.15247977 0.1945291  0.13505813]
[0.00856781 0.         0.         ... 0.20633341 0.23132858 0.21134128]
[0.01558056 0.01161306 0.         ... 0.20641334 0.29057154 0.19576707]
[0.14661269 0.05652344 0.02144914 ... 0.2533615  0.26038733 0.17603636]
[0.06962125 0.         0.11533806 ... 0.1463257  0.21958447 0.15040915]
[0.         0.         0.         ... 0.11596005 0.13538775 0.1411825 ]
[0.         0.         0.  

get frame 205
[0.4        0.24184254 0.01384023 ... 0.15410878 0.13042742 0.11947247]
[0.11252651 0.02259965 0.10813101 ... 0.18340781 0.18013746 0.17230773]
[0.4        0.18609604 0.00349005 ... 0.17436518 0.13205412 0.12116733]
[0.00624714 0.00227243 0.         ... 0.17607136 0.18198    0.17543514]
[0.08924352 0.05224635 0.00167276 ... 0.1648808  0.18324567 0.15746386]
[0.01216123 0.03365881 0.00072252 ... 0.20202327 0.23191471 0.21210977]
[0.39489383 0.3333319  0.1964255  ... 0.1932786  0.2508147  0.1705548 ]
[0.37901673 0.22126387 0.2748813  ... 0.25191617 0.26835388 0.18433984]
[0.39921743 0.1920325  0.22231892 ... 0.1418749  0.20339312 0.14655013]
[0.         0.00282172 0.         ... 0.13718739 0.14954746 0.14214051]
[0.         0.         0.         ... 0.10858981 0.12470283 0.134689  ]
[0.         0.00423278 0.00401556 ... 0.140814   0.18790773 0.14481905]
[0.         0.         0.         ... 0.1171213  0.13564706 0.10387588]
[0.         0.         0.         ... 0.11778767 0

[0.12586285 0.         0.         ... 0.18685459 0.27509046 0.17938322]
[0.06133436 0.         0.         ... 0.21948895 0.24200328 0.16993743]
[0.4        0.         0.09512438 ... 0.15361896 0.25972268 0.1558413 ]
[0.00127311 0.         0.         ... 0.13222235 0.14142993 0.13588206]
[0.00374426 0.         0.         ... 0.10581306 0.13373207 0.13908312]
[0.00233606 0.00326474 0.         ... 0.16263875 0.21449396 0.16455036]
[0.39953098 0.         0.06938439 ... 0.09398355 0.0767316  0.09393796]
[0.08023375 0.00332237 0.         ... 0.12710679 0.14461936 0.12220041]
[0.23062539 0.1130908  0.17452076 ... 0.1651417  0.14679445 0.16195975]
Processing time: 0.153
get frame 213
[0.32971507 0.33102503 0.10096208 ... 0.16312107 0.14409044 0.12607007]
[0.05818545 0.16434029 0.07407313 ... 0.1821728  0.17979498 0.16152075]
[0.4        0.37432766 0.07256607 ... 0.18199569 0.14137894 0.12576108]
[0.03641478 0.00691639 0.         ... 0.2464513  0.37701347 0.2910307 ]
[0.10331826 0.02688732 0.01

[0.4        0.08734062 0.08120376 ... 0.17533289 0.15073495 0.13375205]
[0.05395597 0.00580796 0.         ... 0.17633905 0.20399208 0.19293486]
[0.13450876 0.02467342 0.03395137 ... 0.15053079 0.20432304 0.1876825 ]
[0.00113123 0.         0.02538234 ... 0.13230567 0.14378266 0.1317006 ]
[0.31969073 0.4        0.2619925  ... 0.22624478 0.3276475  0.19526367]
[0.06979071 0.1014369  0.05428443 ... 0.2000462  0.2104249  0.15167122]
[0.38934335 0.4        0.38803104 ... 0.15018001 0.28230494 0.15371335]
[0.         0.         0.         ... 0.10123048 0.12852949 0.13359632]
[0.00164273 0.         0.         ... 0.07781305 0.16155113 0.21908692]
[0.         0.00015954 0.         ... 0.1414417  0.158396   0.14806691]
[0.         0.         0.         ... 0.12080281 0.18625382 0.125032  ]
[0.         0.         0.         ... 0.10505844 0.12384607 0.11135101]
[0.         0.         0.         ... 0.09224931 0.08086609 0.09705424]
Processing time: 0.127
get frame 221
[0.24343392 0.3370839  0.  

[0.3817483  0.372306   0.08843144 ... 0.15554474 0.14641666 0.1297704 ]
[0.06847674 0.10065778 0.00939576 ... 0.1817292  0.18822229 0.18316045]
[0.38355872 0.12313106 0.09636469 ... 0.16264588 0.14457764 0.13118553]
[0.04296309 0.01400866 0.05207333 ... 0.21124083 0.25138918 0.24281842]
[0.17982265 0.04886576 0.02681658 ... 0.15950797 0.19738501 0.16841988]
[0.         0.00649843 0.00307235 ... 0.19197768 0.28053528 0.24185617]
[0.17518958 0.01154163 0.02064629 ... 0.22375101 0.2858248  0.17290187]
[0.         0.         0.0384277  ... 0.26701885 0.26056787 0.16530931]
[0.35814252 0.01881147 0.09609662 ... 0.18014452 0.26412052 0.18137161]
[0.         0.         0.         ... 0.09918524 0.13845168 0.15824431]
[0.         0.         0.         ... 0.08214168 0.14066762 0.18405896]
[0.         0.         0.00021077 ... 0.14746    0.17824395 0.16930911]
[0.4        0.00993377 0.         ... 0.11130039 0.14805001 0.10634699]
[0.3258103  0.00899425 0.         ... 0.07854497 0.0854834  0.07

get frame 236
[0.29576647 0.2756824  0.0041754  ... 0.15095808 0.13881685 0.12794761]
[0.11977969 0.05356975 0.         ... 0.18031585 0.16802756 0.16385485]
[0.4        0.03745239 0.12844625 ... 0.15944223 0.12846282 0.1165092 ]
[0.01072041 0.05888967 0.00479131 ... 0.18919832 0.21428841 0.19929655]
[0.0763019  0.11180904 0.01342417 ... 0.15424484 0.17399028 0.15188035]
[0.         0.00564832 0.         ... 0.189908   0.26639974 0.20753989]
[0.4        0.05820958 0.26015913 ... 0.23365384 0.29017466 0.20506401]
[0.4        0.         0.01454976 ... 0.2731064  0.25785094 0.19278921]
[0.35762903 0.20460476 0.12940341 ... 0.17552598 0.26125973 0.18150395]
[0.         0.00637079 0.         ... 0.10570489 0.129272   0.13488467]
[0.         0.         0.         ... 0.09049984 0.13157268 0.16828746]
[0.         0.00061128 0.         ... 0.14528643 0.1618868  0.1511841 ]
[0.         0.         0.         ... 0.12321873 0.19311512 0.1145892 ]
[0.         0.         0.         ... 0.09506518 0

[0.3999545  0.33890733 0.17595333 ... 0.16981564 0.15319563 0.13687623]
[0.05104012 0.0353399  0.05703246 ... 0.17319728 0.15744211 0.15588723]
[0.4        0.23372355 0.0522557  ... 0.1743161  0.13886033 0.1267478 ]
[0.06366421 0.05127918 0.00072151 ... 0.1475426  0.18100356 0.14222644]
[0.22667035 0.01853804 0.02706966 ... 0.12092946 0.15813251 0.12021794]
[0.00728432 0.00656035 0.00353197 ... 0.1850342  0.20070942 0.19180892]
[0.         0.         0.         ... 0.22136423 0.30968785 0.20051762]
[0.02788427 0.         0.         ... 0.2524998  0.24514161 0.18350361]
[0.06065814 0.         0.05004041 ... 0.1567543  0.2801857  0.15282117]
[0.00035818 0.         0.01093035 ... 0.12381592 0.13214245 0.12558863]
[0.         0.         0.         ... 0.11806419 0.12236355 0.12206966]
[0.00886006 0.00049529 0.         ... 0.15042023 0.1707275  0.14703448]
[0.         0.         0.         ... 0.12680686 0.17246498 0.11937607]
[0.         0.         0.         ... 0.07772969 0.08269962 0.07

[0.16600843 0.05439296 0.10255214 ... 0.1767374  0.15808487 0.15555558]
[0.4        0.10207811 0.06474032 ... 0.17668803 0.13705167 0.12591437]
[0.0301175  0.00889445 0.00596658 ... 0.29123425 0.2815456  0.27347878]
[0.09454966 0.08165573 0.         ... 0.16261494 0.16980758 0.14698766]
[0.00828992 0.         0.00542102 ... 0.29314864 0.2760089  0.2717961 ]
[0.10968056 0.         0.         ... 0.18482853 0.30844814 0.19510104]
[0.23672777 0.20305592 0.         ... 0.20862243 0.22086205 0.18161799]
[0.         0.         0.         ... 0.13136731 0.23837207 0.13982145]
[0.0095388  0.         0.         ... 0.10810476 0.11132429 0.11109667]
[0.         0.00402407 0.         ... 0.09796491 0.11403163 0.12769912]
[0.02696661 0.         0.         ... 0.13144988 0.14291579 0.13377191]
[0.         0.         0.         ... 0.12754568 0.12343619 0.12385844]
[0.         0.         0.         ... 0.10972772 0.12648748 0.1104747 ]
[0.         0.         0.         ... 0.12673526 0.10874736 0.12

[0.15956563 0.         0.21474084 ... 0.15881158 0.20795503 0.16026135]
[0.         0.         0.         ... 0.11072738 0.11272051 0.11304533]
[0.00069505 0.         0.         ... 0.10641254 0.12173469 0.12945788]
[0.         0.00128258 0.         ... 0.11800126 0.12401021 0.1182183 ]
[0.         0.         0.         ... 0.1421332  0.15377218 0.14074205]
[0.         0.         0.         ... 0.09505406 0.09623495 0.09296509]
[0.         0.         0.         ... 0.1303129  0.12679558 0.11536069]
[0.         0.         0.         ... 0.15902996 0.15914334 0.08660954]
[0.03591277 0.01480676 0.         ... 0.15069225 0.14235677 0.10178638]
[0.         0.         0.         ... 0.12124729 0.1413627  0.10623177]
Processing time: 0.157
get frame 258
[0.3809497  0.33371857 0.09436517 ... 0.14075801 0.12908842 0.11812647]
[0.08703865 0.06683207 0.01233394 ... 0.17849463 0.14628686 0.14889881]
[0.4        0.18742424 0.02758032 ... 0.15904385 0.12019555 0.11342385]
[0.         0.00271936 0.  

[0.4        0.         0.03619519 ... 0.13858129 0.11099371 0.11082801]
[0.01268425 0.         0.         ... 0.11839574 0.12613238 0.12531698]
[0.         0.         0.         ... 0.1020941  0.13684678 0.16207442]
[0.         0.         0.         ... 0.12879193 0.14192148 0.13210638]
[0.         0.         0.         ... 0.11300415 0.14283262 0.11422825]
[0.         0.         0.         ... 0.09352022 0.10207677 0.09628157]
[0.04113594 0.         0.01939167 ... 0.11307342 0.1453934  0.10225751]
[0.01761343 0.0019084  0.00521002 ... 0.15654805 0.14148857 0.09974274]
[0.01068131 0.05170408 0.03915896 ... 0.16456328 0.14728603 0.1283839 ]
[0.         0.         0.         ... 0.1407966  0.14638261 0.09025759]
Processing time: 0.146
get frame 265
[0.4        0.17833069 0.05646193 ... 0.1637021  0.14647797 0.13244128]
[0.04256547 0.07732908 0.05246    ... 0.18003297 0.16618064 0.15194666]
[0.4        0.18286236 0.0522242  ... 0.17993212 0.14185818 0.12728027]
[0.02577155 0.00467094 0.00

[0.         0.         0.         ... 0.10517693 0.12105709 0.13554148]
[6.1792140e-05 0.0000000e+00 0.0000000e+00 ... 1.6392066e-01 2.0023303e-01
 1.6995870e-01]
[0.3713947  0.15367092 0.05102476 ... 0.12148876 0.15592025 0.11785992]
[0.13890034 0.         0.04388436 ... 0.12093421 0.12708434 0.12093943]
[0.4        0.07478531 0.07432604 ... 0.10891671 0.09592769 0.10391089]
[0.01233917 0.02200645 0.0380762  ... 0.16902933 0.18867567 0.12510978]
[0.01457878 0.06639796 0.03517934 ... 0.16058654 0.17337166 0.1649433 ]
[0.00854479 0.         0.         ... 0.135584   0.1428784  0.10025033]
Processing time: 0.172
get frame 272
[0.09578251 0.08757329 0.04348661 ... 0.17161907 0.15531138 0.16062023]
[0.00105013 0.00323994 0.         ... 0.19079639 0.1538247  0.15258212]
[0.3861253  0.06971174 0.16877301 ... 0.13136649 0.12322453 0.120757  ]
[0.02699528 0.02514059 0.00650661 ... 0.21567568 0.23530841 0.22076479]
[0.2553599  0.08459371 0.         ... 0.17198277 0.2213042  0.1665191 ]
[0.     

[0.         0.02334648 0.         ... 0.09761196 0.09988575 0.07602207]
Processing time: 0.139
get frame 278
[0.3922723  0.3530557  0.07010197 ... 0.12726998 0.12042256 0.1180537 ]
[0.01123973 0.09260231 0.04755643 ... 0.1750694  0.16879216 0.16630323]
[0.354802   0.08498931 0.1214858  ... 0.15776968 0.12060312 0.11601437]
[0.08127949 0.00213601 0.         ... 0.19068703 0.2153966  0.20093846]
[0.25028205 0.00217935 0.         ... 0.15805314 0.22663984 0.15028511]
[0.00592574 0.00140482 0.         ... 0.22859567 0.287379   0.24024434]
[0.08518479 0.         0.39523363 ... 0.24141276 0.17888997 0.17965384]
[0.05779678 0.         0.14178866 ... 0.2893094  0.17733897 0.17657411]
[0.26480106 0.04585074 0.28843462 ... 0.19817114 0.1410859  0.14034975]
[0.         0.         0.         ... 0.16469394 0.17703746 0.17669514]
[0.         0.         0.         ... 0.11071119 0.14806493 0.16332178]
[0.00361454 0.         0.         ... 0.14948353 0.16615553 0.15332049]
[0.38609105 0.05862563 0.03

get frame 285
[0.317288   0.2191046  0.20546815 ... 0.14356339 0.12610005 0.11952394]
[0.08261282 0.08064739 0.05545393 ... 0.18009976 0.18232605 0.16941912]
[0.37635383 0.2207918  0.126569   ... 0.15517196 0.12045478 0.11879338]
[0.08055399 0.02957674 0.         ... 0.22546604 0.25206986 0.24111015]
[0.29272243 0.0156268  0.0512273  ... 0.19818519 0.22727527 0.17922886]
[0.         0.00354741 0.00346455 ... 0.21002257 0.25414574 0.22044863]
[0.4        0.4        0.13861878 ... 0.20754576 0.21860883 0.20573975]
[0.4        0.35661277 0.30240738 ... 0.27364278 0.22375336 0.2179529 ]
[0.36715427 0.22023878 0.19683993 ... 0.18779033 0.18137084 0.17145781]
[0.         0.         0.         ... 0.11361744 0.11792025 0.11774592]
[0.         0.03265253 0.         ... 0.09544119 0.11358825 0.13341795]
[0.00065964 0.         0.         ... 0.14363904 0.15789215 0.14759512]
[0.4        0.14475511 0.02080709 ... 0.12462188 0.16481149 0.12073015]
[0.4        0.11997807 0.03902441 ... 0.09478988 0