In [3]:
%matplotlib notebook
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from glue import BlindNavigator
from utility import read_video
from PIL import Image
import numpy as np
import cv2
import time

class Visor(object):
    def __init__(self, form = 'OFFLINE'):
        self.form = form
        self.handler = None
        self.handler2 = None
        self.rescale = True
        self.output_size = (600, 400)
        self.im_size = self.output_size


        
    def initializer(self):
        if self.form == 'OFFLINE':
            self.fourcc = cv2.VideoWriter_fourcc(*'XVID')
            writer = None
            (h, w) = (None, None)
            self.handler = writer 
            
        else:
            fig = plt.figure(figsize=(16, 10))
            ax = fig.add_axes([0,0,1,1])

            plt.ion()
            fig.show()
            fig.canvas.draw()
            self.handler = fig
            self.handler2 = ax

            
    def inliner(self, im, save_path='./test.avi'):
        self.im_size = (im.shape[1], im.shape[0])
        (w, h) =  self.output_size

        if self.rescale:
            im = cv2.resize(im, (w, h),interpolation=cv2.INTER_CUBIC)
        else:
            (h, w) = im.shape[:2]

        if self.form == 'OFFLINE' and self.handler is None:
            self.handler = cv2.VideoWriter(save_path, self.fourcc, 30, (w, h), True)
        elif self.form != 'OFFLINE':
            im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
        return im

    def drawer(self, im):
        if self.form == 'OFFLINE':
            self.handler.write(im)
        else:
            self.handler2.imshow(im)
            self.handler.canvas.draw()
            self.handler2.clear()
            
    def rescale_box(self, bbox):
        if self.rescale:
            bbox = np.array([bbox[0] / self.im_size[0] * self.output_size[0], \
                             bbox[1] / self.im_size[1] * self.output_size[1], \
                             bbox[2] / self.im_size[0] * self.output_size[0], \
                             bbox[3] / self.im_size[1] * self.output_size[1]])
        bbox = bbox.astype(int)
        return bbox
    
debuger = 'OFFLINE'
def test_det_track():
    video_path = 'data/IMG_1051.MOV'
    save_path = 'IMG_1051_det_track.avi'

    visor = Visor(debuger)
    visor.initializer()

    navigator = BlindNavigator()
    timestamps = [time.time()]
    for data in read_video(video_path):
        timestamps.append(time.time())

        traffic_lights, detected_obstacles = navigator.detect_traffic_light(data)
        timestamps.append(time.time())
        print('Processing time: %.3f'%(timestamps[-1] - timestamps[-2]))
#         data = cv2.cvtColor(data, cv2.COLOR_BGR2RGB)
        data = visor.inliner(data, save_path)
        for (id_, bbox) in traffic_lights:
            bbox = visor.rescale_box(bbox)
            assert  id_ < len(navigator.traffic_light_pool.trackers), 'id_ not valid'
#             bbox = [bbox[0] / data.shape[1], bbox[1] / data.shape[0], bbox[2] / data.shape[1], bbox[3] / data.shape[0]]
#             print(bbox)
#             p = patches.Rectangle((bbox[0], bbox[1]), bbox[2]-bbox[0], bbox[3]-bbox[1], fill=False, alpha=1)
#             ax.add_patch(p)
            cv2.rectangle(data, tuple(bbox[:2]),tuple(bbox[2:4]), [255, 0, 0], 3)
        visor.drawer(data)

def test_light_classifier(video_path, save_path):


    visor = Visor(debuger)
    visor.initializer()
    navigator = BlindNavigator()
    for data in read_video(video_path):
        traffic_lights, detected_obstacles = navigator.detect_traffic_light(data)
        light_states = navigator.color_classify_by_boxes(data, [light[1] for light in traffic_lights])
        
        data = visor.inliner(data, save_path)
        for (id_, bbox), state in zip(traffic_lights, light_states):
            
            bbox = visor.rescale_box(bbox)

            assert  id_ < len(navigator.traffic_light_pool.trackers), 'id_ not valid'
#             bbox = [bbox[0] / data.shape[1], bbox[1] / data.shape[0], bbox[2] / data.shape[1], bbox[3] / data.shape[0]]
#             print(bbox)
#             p = patches.Rectangle((bbox[0], bbox[1]), bbox[2]-bbox[0], bbox[3]-bbox[1], fill=False, alpha=1)
#             ax.add_patch(p)
            cv2.rectangle(data, tuple(bbox[:2]),tuple(bbox[2:4]), [255, 0, 0], 3)
            font = cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(data, '%s'%(state), (bbox[0]-1,bbox[1]-1), font, 1, color=(255,255,0), thickness=2)
        visor.drawer(data)

def test_zebra_contours(video_path, save_path):

    visor = Visor(debuger)
    visor.initializer()
    navigator = BlindNavigator()
    for data in read_video(video_path):
        p_lights, detected_obstacles = navigator.executor(data)
        data = visor.inliner(data, save_path)
        if p_lights is not None:
            bbox, state  = p_lights.get_bbox(), p_lights.get_state()
            print(bbox)
            bbox = visor.rescale_box(bbox)
            print(bbox)
#             assert  id_ < len(navigator.traffic_light_pool.trackers), 'id_ not valid'
            cv2.rectangle(data, tuple(bbox[:2]),tuple(bbox[2:4]), [255, 0, 0], 3)
            font = cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(data, '%s'%(state), (bbox[0]-1,bbox[1]-1), font, 1, color=(255,255,0), thickness=2)

        for j in navigator.zebra_contours:
            bx, by, bw, bh = cv2.boundingRect(j)
            [bx, by, bw, bh] = visor.rescale_box([bx, by, bw, bh])
            cv2.rectangle(data, (bx, by), (bx + bw, by + bh), (180, 237, 167), -1)
        visor.drawer(data)


if __name__ == '__main__':
    video_path = 'data/IMG_9033.m4v'
    save_path = 'IMG_9033_zebra_track.avi'
    test_zebra_contours(video_path, save_path)

keras_yolo3/model_data/yolo.h5 model, anchors, and classes loaded.
get frame 0
Detected 0 traffic lights, in total 0 traffic lights, 1 obstacles
[]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 0
get frame 1
Detected 0 traffic lights, in total 0 traffic lights, 1 obstacles
[]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 0
get frame 2
Detected 0 traffic lights, in total 0 traffic lights, 1 obstacles
[]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 0
get frame 3
Detected 0 traffic lights, in total 0 traffic lights, 1 obstacles
[]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 0
get frame 4
Detected 0 traffic lights, in total 0 traffic lights, 1 obstacles
[]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 0
get frame 5
Detected 0 traffic lights, in total 0 traffic lights, 1 obstacles
[]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 0
get frame 6
Detected 0 traffic li

Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 20, Forward Max Pedestrain Light vote 21
Tracker 0 has been determined as pedestrain light 21 times 
[661, 261, 679, 297]
[309 145 318 165]
get frame 43
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[2]
Cur Max Pedestrain Light vote 21, Forward Max Pedestrain Light vote 21
[660, 262, 679, 299]
[309 145 318 166]
get frame 44
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[2]
Cur Max Pedestrain Light vote 21, Forward Max Pedestrain Light vote 21
[660, 262, 680, 300]
[309 145 318 166]
get frame 45
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[2]
Cur Max Pedestrain Light vote 21, Forward Max Pedestrain Light vote 21
[659, 262, 679, 300]
[308 145 318 166]
get frame 46
Detected 1 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 21, Forward Max Pedestrain Light vote 21
[659, 262, 678, 300]
[308 1

Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 43, Forward Max Pedestrain Light vote 44
Tracker 0 has been determined as pedestrain light 44 times 
[659, 261, 678, 301]
[308 145 317 167]
get frame 73
Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 44, Forward Max Pedestrain Light vote 45
Tracker 0 has been determined as pedestrain light 45 times 
[660.4344994079441, 263.88305018523107, 677.4344994079441, 296.88305018523107]
[309 146 317 164]
get frame 74
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 45, Forward Max Pedestrain Light vote 46
Tracker 0 has been determined as pedestrain light 46 times 
[660, 261, 680, 302]
[309 145 318 167]
get frame 75
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 46, Forward Max Pedestrain Light vote 47
Tracker 0 has been determined as pedestrai

[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 68
Tracker 0 has been determined as pedestrain light 68 times 
[675.4228486259667, 273.83355145609835, 692.4228486259667, 306.83355145609835]
[316 152 324 170]
get frame 103
Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 69
Tracker 0 has been determined as pedestrain light 69 times 
[675.9058204017992, 274.615203340867, 692.9058204017992, 307.615203340867]
[316 152 324 170]
get frame 104
Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 70
Tracker 0 has been determined as pedestrain light 70 times 
[676.2280718968785, 275.02028978587373, 693.2280718968785, 308.02028978587373]
[316 152 324 171]
get frame 105
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 

Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 92
Tracker 0 has been determined as pedestrain light 92 times 
[681.1269583581708, 292.30421621443634, 698.1269583581708, 325.30421621443634]
[319 162 327 180]
get frame 131
Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 93
Tracker 0 has been determined as pedestrain light 93 times 
[680.8384655697314, 291.4481312501886, 697.8384655697314, 324.4481312501886]
[319 161 327 180]
get frame 132
Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 94
Tracker 0 has been determined as pedestrain light 94 times 
[680.8703758915537, 291.63905490334605, 697.8703758915537, 324.63905490334605]
[319 162 327 180]
get frame 133
Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]

Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 118
Tracker 0 has been determined as pedestrain light 118 times 
[686.4568192614884, 281.1885140638557, 703.4568192614884, 314.1885140638557]
[321 156 329 174]
get frame 159
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 119
Tracker 0 has been determined as pedestrain light 119 times 
[687, 281, 705, 312]
[322 156 330 173]
get frame 160
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 120
Tracker 0 has been determined as pedestrain light 120 times 
[687, 281, 705, 312]
[322 156 330 173]
get frame 161
Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 121
Tracker 0 has been determined as pedes

Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 150
Tracker 0 has been determined as pedestrain light 150 times 
[694, 289, 713, 324]
[325 160 334 180]
get frame 191
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 151
Tracker 0 has been determined as pedestrain light 151 times 
[694, 289, 713, 324]
[325 160 334 180]
get frame 192
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 152
Tracker 0 has been determined as pedestrain light 152 times 
[694, 289, 713, 324]
[325 160 334 180]
get frame 193
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 153
Tracker 0 has been determined as pedestrain light 153 times 
[695, 289, 713, 324]
[325 160 334

Detected 0 traffic lights, in total 1 traffic lights, 4 obstacles
[2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 164
Tracker 0 has been determined as pedestrain light 164 times 
[691.2643396522309, 272.9309587029661, 708.2643396522309, 305.9309587029661]
[324 151 331 169]
get frame 225
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 165
Tracker 0 has been determined as pedestrain light 165 times 
[691.1489722456575, 272.7368962109204, 708.1489722456575, 305.7368962109204]
[323 151 331 169]
get frame 226
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 166
Tracker 0 has been determined as pedestrain light 166 times 
[690.8574305355094, 272.4439934248474, 707.8574305355094, 305.4439934248474]
[323 151 331 169]
get frame 227
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[

Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 192
Tracker 0 has been determined as pedestrain light 192 times 
[686, 263, 705, 300]
[321 146 330 166]
get frame 253
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 193
Tracker 0 has been determined as pedestrain light 193 times 
[686, 263, 706, 300]
[321 146 330 166]
get frame 254
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 194
Tracker 0 has been determined as pedestrain light 194 times 
[686, 263, 706, 300]
[321 146 330 166]
get frame 255
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 195
Tracker 0 has been determined as pedestrain light 195 times 
[686, 263, 706, 300]
[321 146 330

Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 223, Forward Max Pedestrain Light vote 224
Tracker 0 has been determined as pedestrain light 224 times 
[689, 268, 707, 299]
[322 148 331 166]
get frame 285
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 224, Forward Max Pedestrain Light vote 225
Tracker 0 has been determined as pedestrain light 225 times 
[689, 269, 707, 299]
[322 149 331 166]
get frame 286
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 225, Forward Max Pedestrain Light vote 226
Tracker 0 has been determined as pedestrain light 226 times 
[689, 268, 707, 299]
[322 148 331 166]
get frame 287
Detected 1 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 226, Forward Max Pedestrain Light vote 227
Tracker 0 has been determined as pedestrain light 227 times 
[689, 268, 707, 300]
[322

Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 255, Forward Max Pedestrain Light vote 256
Tracker 0 has been determined as pedestrain light 256 times 
[690.2921246923764, 261.61514505746635, 707.2921246923764, 294.61514505746635]
[323 145 331 163]
get frame 317
Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 256, Forward Max Pedestrain Light vote 257
Tracker 0 has been determined as pedestrain light 257 times 
[690.7014144213371, 261.0305140676632, 707.7014144213371, 294.0305140676632]
[323 145 331 163]
get frame 318
Detected 0 traffic lights, in total 1 traffic lights, 2 obstacles
[1]
Cur Max Pedestrain Light vote 257, Forward Max Pedestrain Light vote 258
Tracker 0 has been determined as pedestrain light 258 times 
[690.6265144599818, 260.14013897465213, 707.6265144599818, 293.14013897465213]
[323 144 331 162]
get frame 319
Detected 0 traffic lights, in total 1 traffic lights, 2 o

Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 287, Forward Max Pedestrain Light vote 288
Tracker 0 has been determined as pedestrain light 288 times 
[669, 257, 687, 291]
[313 142 322 161]
get frame 349
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 288, Forward Max Pedestrain Light vote 289
Tracker 0 has been determined as pedestrain light 289 times 
[668, 257, 687, 291]
[313 142 322 161]
get frame 350
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 289, Forward Max Pedestrain Light vote 290
Tracker 0 has been determined as pedestrain light 290 times 
[667, 257, 686, 292]
[312 142 321 162]
get frame 351
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[2]
Cur Max Pedestrain Light vote 290, Forward Max Pedestrain Light vote 290
[666, 256, 685, 291]
[312 142 321 161]
get frame 352
Detected 1 traffic lights, in tot

/home/changcheng/xthu/Zebra.py:19: RuntimeWarning: divide by zero encountered in true_divide
  m = (y1-y0)/(x1-x0)
/home/changcheng/xthu/Zebra.py:39: RuntimeWarning: invalid value encountered in subtract
  dy = a_1*c_2 - a_2*c_1
/home/changcheng/xthu/Zebra.py:41: RuntimeWarning: invalid value encountered in true_divide
  intersectionX = dx/d
/home/changcheng/xthu/Zebra.py:19: RuntimeWarning: divide by zero encountered in true_divide
  m = (y1-y0)/(x1-x0)
/home/changcheng/xthu/Zebra.py:39: RuntimeWarning: invalid value encountered in subtract
  dy = a_1*c_2 - a_2*c_1
/home/changcheng/xthu/Zebra.py:41: RuntimeWarning: invalid value encountered in true_divide
  intersectionX = dx/d


Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 290, Forward Max Pedestrain Light vote 290
[658.207987625401, 259.53813448458385, 676.057987625401, 294.1881344845838]
[308 144 316 163]
get frame 365
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 290, Forward Max Pedestrain Light vote 290
[657.5331490667133, 259.7203690160523, 675.3831490667134, 294.3703690160523]
[308 144 316 163]
get frame 366
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 290, Forward Max Pedestrain Light vote 290
[657.301583684422, 260.0411041279651, 675.151583684422, 294.6911041279651]
[308 144 316 163]
get frame 367
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 290, Forward Max Pedestrain Light vote 290
[656.6583645521855, 260.39612583874066, 674.5083645521855, 295.04612583874064]
[307 144 316 163]
get fra

Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 310, Forward Max Pedestrain Light vote 311
Tracker 0 has been determined as pedestrain light 311 times 
[645, 259, 662, 293]
[302 143 310 162]
get frame 397
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 311, Forward Max Pedestrain Light vote 312
Tracker 0 has been determined as pedestrain light 312 times 
[645, 259, 662, 292]
[302 143 310 162]
get frame 398
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 312, Forward Max Pedestrain Light vote 313
Tracker 0 has been determined as pedestrain light 313 times 
[646, 259, 662, 292]
[302 143 310 162]
get frame 399
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 313, Forward Max Pedestrain Light vote 314
Tracker 0 has been determined as pedestrain light 314 times 
[646, 259, 662, 291]
[302

Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 340, Forward Max Pedestrain Light vote 341
Tracker 0 has been determined as pedestrain light 341 times 
[654.7440918339322, 252.74435195597766, 671.7440918339322, 285.74435195597766]
[306 140 314 158]
get frame 427
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 341, Forward Max Pedestrain Light vote 342
Tracker 0 has been determined as pedestrain light 342 times 
[652, 251, 670, 283]
[305 139 314 157]
get frame 428
Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 342, Forward Max Pedestrain Light vote 343
Tracker 0 has been determined as pedestrain light 343 times 
[654.9706763748784, 252.68621795718923, 671.9706763748784, 285.6862179571892]
[307 140 314 158]
get frame 429
Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 343, Forward M

Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 368, Forward Max Pedestrain Light vote 369
Tracker 0 has been determined as pedestrain light 369 times 
[656.9728311994996, 253.34686832826438, 673.9728311994996, 286.34686832826435]
[307 140 315 159]
get frame 455
Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[1]
Cur Max Pedestrain Light vote 369, Forward Max Pedestrain Light vote 370
Tracker 0 has been determined as pedestrain light 370 times 
[657.2116986488082, 253.49423100693994, 674.2116986488082, 286.4942310069399]
[308 140 316 159]
get frame 456
Detected 0 traffic lights, in total 1 traffic lights, 1 obstacles
[2]
Cur Max Pedestrain Light vote 370, Forward Max Pedestrain Light vote 370
[657.4673253855265, 253.89844335084058, 674.4673253855265, 286.8984433508406]
[308 141 316 159]
get frame 457
Detected 1 traffic lights, in total 1 traffic lights, 1 obstacles
[2]
Cur Max Pedestrain Light vote 370, Forward Max P

Detected 1 traffic lights, in total 1 traffic lights, 4 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[669, 258, 686, 292]
[313 143 321 162]
get frame 493
Detected 1 traffic lights, in total 1 traffic lights, 4 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[670, 258, 687, 293]
[314 143 322 162]
get frame 494
Detected 1 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[670, 259, 687, 294]
[314 143 322 163]
get frame 495
Detected 1 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[670, 259, 688, 294]
[314 143 322 163]
get frame 496
Detected 1 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[671, 259, 688, 294]
[314 143 322 163]
get frame 497
Detected 1 traffic l

Detected 0 traffic lights, in total 1 traffic lights, 6 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[684.1031656042272, 250.29592219336539, 701.9531656042273, 284.9459221933654]
[320 139 329 158]
get frame 531
Detected 0 traffic lights, in total 1 traffic lights, 7 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[684.680112202782, 250.54403701010312, 701.680112202782, 283.5440370101031]
[320 139 328 157]
get frame 532
Detected 1 traffic lights, in total 1 traffic lights, 8 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[685, 248, 705, 282]
[321 137 330 156]
get frame 533
Detected 1 traffic lights, in total 1 traffic lights, 8 obstacles
[2]
Cur Max Pedestrain Light vote 379, Forward Max Pedestrain Light vote 379
[685, 248, 705, 282]
[321 137 330 156]
get frame 534
Detected 0 traffic lights, in total 1 traffic lights, 7 obstacles
[2]
Cur Max Pedestrain Light vote 379,

Detected 1 traffic lights, in total 1 traffic lights, 7 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[676, 240, 697, 275]
[316 133 326 152]
get frame 569
Detected 0 traffic lights, in total 1 traffic lights, 6 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[682.010827670457, 239.68492611968924, 699.010827670457, 272.68492611968924]
[319 133 327 151]
get frame 570
Detected 0 traffic lights, in total 1 traffic lights, 7 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[681.5185267652538, 239.39439421134634, 698.5185267652538, 272.39439421134637]
[319 132 327 151]
get frame 571
Detected 0 traffic lights, in total 1 traffic lights, 6 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[680.5580044175251, 238.0261851732981, 698.4080044175251, 272.6761851732981]
[319 132 327 151]
get frame 572
Detected 0 traffic lights, in total 1 traffic 

Detected 1 traffic lights, in total 1 traffic lights, 8 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[667, 231, 687, 263]
[312 128 322 146]
get frame 609
Detected 1 traffic lights, in total 1 traffic lights, 7 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[667, 231, 688, 263]
[312 128 322 146]
get frame 610
Detected 1 traffic lights, in total 1 traffic lights, 6 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[667, 231, 688, 262]
[312 128 322 145]
get frame 611
Detected 1 traffic lights, in total 1 traffic lights, 7 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[667, 231, 688, 263]
[312 128 322 146]
get frame 612
Detected 1 traffic lights, in total 1 traffic lights, 8 obstacles
[2]
Cur Max Pedestrain Light vote 382, Forward Max Pedestrain Light vote 382
[667, 231, 688, 263]
[312 128 322 146]
get frame 613
Detected 1 traffic l

Detected 1 traffic lights, in total 1 traffic lights, 5 obstacles
[2]
Cur Max Pedestrain Light vote 385, Forward Max Pedestrain Light vote 385
[667, 230, 687, 262]
[312 127 322 145]
get frame 647
Detected 1 traffic lights, in total 1 traffic lights, 4 obstacles
[2]
Cur Max Pedestrain Light vote 385, Forward Max Pedestrain Light vote 385
[667, 230, 687, 262]
[312 127 322 145]
get frame 648
Detected 1 traffic lights, in total 1 traffic lights, 4 obstacles
[2]
Cur Max Pedestrain Light vote 385, Forward Max Pedestrain Light vote 385
[667, 230, 687, 262]
[312 127 322 145]
get frame 649
Detected 1 traffic lights, in total 1 traffic lights, 5 obstacles
[2]
Cur Max Pedestrain Light vote 385, Forward Max Pedestrain Light vote 385
[666, 230, 688, 262]
[312 127 322 145]
get frame 650
Detected 1 traffic lights, in total 1 traffic lights, 4 obstacles
[2]
Cur Max Pedestrain Light vote 385, Forward Max Pedestrain Light vote 385
[667, 230, 687, 262]
[312 127 322 145]
get frame 651
Detected 1 traffic l

Detected 0 traffic lights, in total 1 traffic lights, 4 obstacles
[2]
Cur Max Pedestrain Light vote 389, Forward Max Pedestrain Light vote 389
[668.6106759546918, 228.1187535568583, 685.6106759546918, 261.11875355685834]
[313 126 321 145]
get frame 685
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 389, Forward Max Pedestrain Light vote 389
[668.2457828719871, 227.62491252525706, 685.2457828719871, 260.62491252525706]
[313 126 321 144]
get frame 686
Detected 1 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 389, Forward Max Pedestrain Light vote 389
[664, 226, 686, 264]
[311 125 321 146]
get frame 687
Detected 0 traffic lights, in total 1 traffic lights, 3 obstacles
[2]
Cur Max Pedestrain Light vote 389, Forward Max Pedestrain Light vote 389
[668.5003539721469, 227.68759533303282, 685.5003539721469, 260.68759533303285]
[313 126 321 144]
get frame 688
Detected 0 traffic lights, in total 1 traff

Detected 1 traffic lights, in total 1 traffic lights, 4 obstacles
[1]
Cur Max Pedestrain Light vote 401, Forward Max Pedestrain Light vote 402
Tracker 0 has been determined as pedestrain light 402 times 
[660, 190, 682, 230]
[309 105 319 127]
get frame 721
Detected 1 traffic lights, in total 1 traffic lights, 4 obstacles
[1]
Cur Max Pedestrain Light vote 402, Forward Max Pedestrain Light vote 403
Tracker 0 has been determined as pedestrain light 403 times 
[659, 190, 679, 229]
[308 105 318 127]
get frame 722
Detected 2 traffic lights, in total 2 traffic lights, 3 obstacles
[1, 0]
Cur Max Pedestrain Light vote 403, Forward Max Pedestrain Light vote 404
Tracker 0 has been determined as pedestrain light 404 times 
[659, 190, 679, 229]
[308 105 318 127]
get frame 723
Detected 1 traffic lights, in total 2 traffic lights, 3 obstacles
[1, 0]
Cur Max Pedestrain Light vote 404, Forward Max Pedestrain Light vote 404
[656.4140698441996, 187.46056627933044, 673.4140698441996, 220.46056627933044]
[

Detected 1 traffic lights, in total 2 traffic lights, 3 obstacles
[2, 2]
Cur Max Pedestrain Light vote 404, Forward Max Pedestrain Light vote 404
[625.2912165798191, 161.532143253455, 643.1412165798191, 196.182143253455]
[293  89 301 108]
get frame 761
Detected 1 traffic lights, in total 2 traffic lights, 2 obstacles
[2, 2]
Cur Max Pedestrain Light vote 404, Forward Max Pedestrain Light vote 404
[622, 158, 640, 199]
[291  87 300 110]
get frame 762
Detected 1 traffic lights, in total 2 traffic lights, 3 obstacles
[2, 2]
Cur Max Pedestrain Light vote 404, Forward Max Pedestrain Light vote 404
[621, 159, 639, 199]
[291  88 299 110]
get frame 763
Detected 1 traffic lights, in total 2 traffic lights, 3 obstacles
[2, 2]
Cur Max Pedestrain Light vote 404, Forward Max Pedestrain Light vote 404
[620, 160, 638, 200]
[290  88 299 111]
get frame 764
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 404, Forward Max Pedestrain Light vote 404
[619

Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 405, Forward Max Pedestrain Light vote 405
[577, 141, 599, 180]
[270  78 280 100]
get frame 802
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 405, Forward Max Pedestrain Light vote 405
[576, 140, 598, 179]
[270  77 280  99]
get frame 803
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 405, Forward Max Pedestrain Light vote 405
[578.8491718421826, 140.1040996833827, 598.5287968421826, 178.30572468338272]
[271  77 280  99]
get frame 804
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 405, Forward Max Pedestrain Light vote 405
[578.0590803859124, 137.8903139489462, 596.8015803859123, 174.27281394894618]
[270  76 279  96]
get frame 805
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrai

Detected 0 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 406, Forward Max Pedestrain Light vote 406
[556.0941667379708, 113.2006435150377, 577.7909533004708, 155.3179350775377]
[260  62 270  86]
get frame 842
Detected 0 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 406, Forward Max Pedestrain Light vote 406
[556.4796444962858, 107.28184319258855, 579.2612703869108, 151.50499933321356]
[260  59 271  84]
get frame 843
Detected 0 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 406, Forward Max Pedestrain Light vote 406
[552.1087634560697, 107.00424600937069, 574.8903893466947, 151.2274021499957]
[258  59 269  84]
get frame 844
Detected 0 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 406, Forward Max Pedestrain Light vote 406
[547.085043113436, 105.85858229949545, 571.0057502985923, 152.2928962471517]
[256  58 

Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 407, Forward Max Pedestrain Light vote 407
[528.2176319323455, 153.5200871425258, 553.3343744767595, 202.27611678756486]
[247  85 259 112]
get frame 876
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 407, Forward Max Pedestrain Light vote 407
[534.6516067442379, 156.20591625325142, 561.0241864158727, 207.39974738054244]
[250  86 262 115]
get frame 877
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 407, Forward Max Pedestrain Light vote 407
[541.1960316425775, 158.88316244001794, 567.5686113142123, 210.07699356730896]
[253  88 266 116]
get frame 878
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 407, Forward Max Pedestrain Light vote 407
[546.9934796499966, 158.49363161748144, 574.6846883052132, 212.24715430113702]
[256 

Detected 1 traffic lights, in total 1 traffic lights, 5 obstacles
[2]
Cur Max Pedestrain Light vote 407, Forward Max Pedestrain Light vote 407
[510.13583640941766, 180.97524132112642, 529.8154614094177, 219.17686632112643]
[239 100 248 121]
get frame 908
Detected 1 traffic lights, in total 1 traffic lights, 5 obstacles
[1]
Cur Max Pedestrain Light vote 407, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[509.9652502890227, 186.20283816229067, 528.7077502890227, 222.58533816229067]
[239 103 247 123]
get frame 909
Detected 1 traffic lights, in total 1 traffic lights, 5 obstacles
[2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[511.20201908799754, 193.71814177519664, 529.0520190879976, 228.36814177519665]
[239 107 247 126]
get frame 910
Detected 1 traffic lights, in total 1 traffic lights, 5 obstacles
[2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[511.2575194906667, 197.97170449

Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[472.8904578142832, 223.07182311329953, 493.5540640642832, 263.18352936329956]
[221 123 231 146]
get frame 940
Detected 1 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[472.8930389830028, 227.68432226532713, 492.57266398300277, 265.8859472653271]
[221 126 230 147]
get frame 941
Detected 1 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[475.7931988665873, 233.86609925718085, 494.5356988665873, 270.24859925718084]
[223 129 231 150]
get frame 942
Detected 0 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[479.7888391643415, 237.2021242623264, 497.6388391643415, 271.8521242623264]
[224 1

get frame 971
Detected 1 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[477.7914995207083, 222.37000481356105, 501.71220670586456, 268.8043187612173]
[223 123 235 149]
get frame 972
Detected 1 traffic lights, in total 1 traffic lights, 7 obstacles
[2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[477.633223396395, 220.5256365337517, 502.7499659408091, 269.2816661787908]
[223 122 235 149]
get frame 973
Detected 1 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[480.82781998437326, 228.69135513003215, 505.94456252878734, 277.4473847750712]
[225 127 237 154]
get frame 974
Detected 0 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[480.5425064162613, 230.3990525733113, 505.65924896067537, 279.15508221835

Detected 0 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[508.1445920783621, 201.29732455763892, 537.2203611663394, 257.73852337547726]
[238 111 251 143]
get frame 1005
Detected 0 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[510.83425065295165, 194.01036027629516, 541.3638081953279, 253.27361903502543]
[239 107 253 140]
get frame 1006
Detected 0 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[511.2032755242255, 192.37428790743846, 543.2593109437205, 254.60070960410525]
[239 106 254 141]
get frame 1007
Detected 0 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[510.3774238409131, 189.9192103069194, 544.0362610313829, 255.25695308841955]
[

Detected 0 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[545.9877478928498, 196.60990972846824, 579.6465850833196, 261.9476525099684]
[255 109 271 145]
get frame 1038
Detected 1 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[542.0268706702426, 190.1679845996242, 575.6857078607123, 255.50572738112433]
[254 105 269 141]
get frame 1039
Detected 1 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[539.084746756248, 189.4205711844384, 572.7435839467178, 254.75831396593853]
[252 105 268 141]
get frame 1040
Detected 1 traffic lights, in total 2 traffic lights, 7 obstacles
[2, 2]
Cur Max Pedestrain Light vote 408, Forward Max Pedestrain Light vote 408
[537.248711701766, 187.017575925189, 570.9075488922357, 252.35531870668913]
[251 103

Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[0, 1]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[561.0213625688043, 153.28985135855137, 591.5509201111805, 212.55311011728165]
[262  85 277 118]
get frame 1071
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[1, 0]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[562.2611442392131, 154.3449909490059, 591.3369133271905, 210.78618976684427]
[263  85 277 117]
get frame 1072
Detected 1 traffic lights, in total 2 traffic lights, 6 obstacles
[1, 0]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[561.9166398500233, 152.14454663734355, 590.9924089380007, 208.58574545518192]
[263  84 277 115]
get frame 1073
Detected 1 traffic lights, in total 2 traffic ligh

Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[586.7015208986334, 152.7349148760723, 614.3927295538499, 206.48843755972788]
[275  84 287 114]
get frame 1098
Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[588.2469540306687, 154.3383220263851, 614.6195337023034, 205.53215315367612]
[275  85 288 114]
get frame 1099
Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[590.155456344225, 155.31071681943789, 615.272198888639, 204.06674646447695]
[276  86 288 113]
get frame 1100
Detected 1 traffic lights, in total 1 traffic lights,

Detected 0 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[529.9304404920019, 166.88681792861047, 556.3030201636367, 218.0806490559015]
[248  92 260 121]
get frame 1124
Detected 0 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[528.3830195418764, 167.43293292348253, 554.7555992135111, 218.62676405077355]
[247  93 260 121]
get frame 1125
Detected 0 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 408
Tracker 0 has been determined as pedestrain light 408 times 
[525.1119103443898, 168.19047107827612, 551.4844900160246, 219.38430220556714]
[246  93 258 121]
get frame 1126
Detected 0 traffic lights, in total 2 traffic ligh

Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[497.70072186439893, 195.49104065045185, 520.482347755024, 239.71419679107686]
[233 108 243 133]
get frame 1150
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[495.19477652375, 197.26161905662, 516.89156308625, 239.37891061912]
[232 109 242 132]
get frame 1151
Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[493.0686165794815, 196.1645513726175, 515.8502424701065, 240.3877075132425]
[231 108 241 133]
get frame 1152
Detected 0 traffic lights, in total 2 traffic lights, 5 obsta

Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[530.6530067466255, 225.37246138888733, 550.3326317466255, 263.57408638888734]
[248 125 257 146]
get frame 1176
Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[530.9953918454831, 228.14005904377976, 550.6750168454831, 266.34168404377976]
[248 126 258 147]
get frame 1177
Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[532.3084072998424, 228.20668456177236, 551.9880322998424, 266.40830956177234]
[249 126 258 148]
get frame 1178
Detected 1 traffic lights, in total 2 traffic lig

Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[1, 0]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[542.9923808919318, 241.9913380541292, 561.7348808919318, 278.3738380541292]
[254 134 263 154]
get frame 1202
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[546.722603904695, 239.50402076054237, 565.465103904695, 275.8865207605424]
[256 133 265 153]
get frame 1203
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[549.4015287562166, 240.85412677774863, 568.1440287562166, 277.23662677774865]
[257 133 266 154]
get frame 1204
Detected 1 traffic lights, in total 2 traffic lights, 

Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[587.837174835831, 237.6983412350037, 602.5224140108661, 266.2049819865424]
[275 132 282 147]
get frame 1229
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[590.2645959856216, 235.27720654871365, 604.9498351606567, 263.7838473002524]
[276 130 283 146]
get frame 1230
Detected 1 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 409
Tracker 0 has been determined as pedestrain light 409 times 
[595.781407123236, 236.9574965407965, 609.767349194698, 264.1066782089286]
[279 131 285 146]
get frame 1231
Detected 0 traffic lights, in total 2 traffic lights, 5 o

Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[599.9238230840871, 234.17137744523149, 619.6034480840871, 272.37300244523146]
[281 130 290 151]
get frame 1255
Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[599.1280490804036, 235.5148494085427, 618.8076740804036, 273.7164744085427]
[280 130 290 152]
get frame 1256
Detected 0 traffic lights, in total 2 traffic lights, 5 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[598.4956888073173, 235.41151709457733, 618.1753138073173, 273.6131420945773]
[280 130 289 152]
get frame 1257
Detected 0 traffic lights, in total 2 traffic lights

Detected 1 traffic lights, in total 2 traffic lights, 6 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[606.6387710817435, 247.62688727457828, 624.4887710817435, 282.27688727457826]
[284 137 292 156]
get frame 1281
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[605.955589364791, 247.90662313069944, 623.805589364791, 282.55662313069945]
[284 137 292 156]
get frame 1282
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[605.1016438954082, 248.93253852953734, 622.9516438954082, 283.5825385295373]
[283 138 292 157]
get frame 1283
Detected 1 traffic lights, in total 2 traffic lights

Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[578.3258982948329, 253.4361006148914, 597.0683982948328, 289.8186006148914]
[271 140 279 161]
get frame 1307
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[577.9032217497357, 252.96914138180063, 596.6457217497357, 289.3516413818006]
[270 140 279 160]
get frame 1308
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[577.5591937929772, 253.82734826513743, 596.3016937929772, 290.20984826513745]
[270 141 279 161]
get frame 1309
Detected 1 traffic lights, in total 2 traffic lights

Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[545.066861292772, 299.4026528894343, 564.746486292772, 337.6042778894343]
[255 166 264 187]
get frame 1333
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[544.4174841218436, 301.28010890689006, 564.0971091218436, 339.48173390689004]
[255 167 264 188]
get frame 1334
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[543.4816397613786, 304.1491483251756, 563.1612647613786, 342.35077332517557]
[254 168 263 190]
get frame 1335
Detected 1 traffic lights, in total 2 traffic lights, 

Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[503.5659228986676, 335.6298718070626, 523.2455478986676, 373.8314968070626]
[236 186 245 207]
get frame 1360
Detected 1 traffic lights, in total 2 traffic lights, 3 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[503.4470553197295, 334.2016679041887, 523.1266803197295, 372.4032929041887]
[235 185 245 206]
get frame 1361
Detected 1 traffic lights, in total 2 traffic lights, 4 obstacles
[2, 2]
Cur Max Pedestrain Light vote 0, Forward Max Pedestrain Light vote 410
Tracker 0 has been determined as pedestrain light 410 times 
[503.8899810265163, 334.92888336034054, 523.5696060265163, 373.1305083603405]
[236 186 245 207]
get frame 1362
Detected 1 traffic lights, in total 2 traffic lights, 

TypeError: 'NoneType' object is not subscriptable